### ISSUE TITLE
curated data for cleaning

### ISSUE THREAD

**Issue by diazrenata** [role-model/multidim-biodiv-data#17]
@diazrenata create linked datasets for abundance and traits

`abundance` has individuals observed, spp

`traits` is a subset of specimens. same species, different typos.

work through taxize cleaning once with abundance

use it as an exercise in the traits episode

**Comment by connor-french** [comment]
Awesome, thanks Renata! I'll push my current edits and test out the traits data.

**Comment by connor-french** [comment]
For the traits, I got three species with typos and one species with the taxonomic problem. The three species were different from yours, but Cirphis amblycasis was the same. I like this- they should remember what the fix for Cirphis is from the abundance episode, so the change shouldn't be difficult. I'll call this finished.
